version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mechanicdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

  backend:
    build: ./backend
    environment:
      DB_URL: jdbc:mysql://db:3306/mechanicdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: secret
      JWT_SECRET: super-secret-change-me
      CORS_ALLOWED_ORIGINS: http://localhost:8081,http://127.0.0.1:8081,http://localhost:5173
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
